version: '3.8'

services:
  app:
    container_name: chatterspire-app
    image: davoola/chatterspire
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/chatterspire
      - SESSION_SECRET=your_secret_key
      - NODE_ENV=production
    volumes:
      - ./public/upload:/app/public/upload
      - ./public/avatar:/app/public/avatar
      - ./records:/app/records
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - chatterspire-network

  mongo:
    container_name: chatterspire-mongo
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: mongod --bind_ip_all
    networks:
      - chatterspire-network

networks:
  chatterspire-network:
    driver: bridge

volumes:
  mongodb_data: 